; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Dokumentverwaltung"
#define MyAppPublisher "BfW OHG"
#define MyAppExeName "dokverwaltung.exe"

#define MyAppVersion GetFileVersion('c:\repositories\Dokumentverwaltung\Win32\Release\dokverwaltung.exe')

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{49A21091-281E-41F0-BA8E-FEF79C567379}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName={#MyAppName}
OutputBaseFilename=setupTESTVERSION{#myappversion}
Compression=lzma
SolidCompression=yes
OutputDir=H:\Melanie\setup\Dokumentverwaltung\


[Languages]
Name: german; MessagesFile: compiler:Languages\German.isl

[Tasks]
Name: desktopicon; Description: {cm:CreateDesktopIcon}; GroupDescription: {cm:AdditionalIcons}; Flags: unchecked

[Files]
Source: c:\repositories\Dokumentverwaltung\Win32\Release\dokverwaltung.exe; DestDir: {app}; Flags: ignoreversion
Source: c:\repositories\Dokumentverwaltung\Win32\Release\libmysql.dll; DestDir: {app}; Flags: ignoreversion
Source: c:\repositories\Dokumentverwaltung\Win32\Release\sqlite3.dll; DestDir: {app}; Flags: ignoreversion
Source: c:\repositories\Dokumentverwaltung\Win32\Release\doppelstart.dcu; DestDir: {app}; Flags: ignoreversion
Source: C:\repositories\Dokumentverwaltung\Win32\Release\plink.exe; DestDir: {app}; Flags: ignoreversion
;Source: C:\Users\jovani\Documents\Embarcadero\Studio\Projekte\ftpcollectorui\Win32\Debug\ftpcollectui.exe; DestDir: {app}; Flags: ignoreversion
Source: C:\repositories\namepipeserver\Win32\Debug\pnamepipeserver.exe; DestDir: {app}; Flags: ignoreversion
Source: c:\repositories\Dokumentverwaltung\Win32\Release\plinkini.bat; DestDir: {app}; Flags: ignoreversion deleteafterinstall
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
Source: c:\repositories\Dokumentverwaltung\Win32\Release\aenderung.txt; DestDir: {commonappdata}; DestName: Dokumentverwaltung/aenderung.txt

[Icons]
Name: {group}\{#MyAppName}; Filename: {app}\{#MyAppExeName}
Name: {commondesktop}\{#MyAppName}; Filename: {app}\{#MyAppExeName}; Tasks: desktopicon

[Run]
Filename: {app}\{#MyAppExeName}; Description: {cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}; Flags: nowait postinstall skipifsilent
Filename: {app}\plinkini.bat; WorkingDir: {app}; Flags: shellexec runhidden

